"""added pin backend

Revision ID: c10257c40af3
Revises: 0bdd0cbc74f6
Create Date: 2023-09-04 09:14:00.718367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10257c40af3'
down_revision = '0bdd0cbc74f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('session_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_long', sa.Float(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pins_id'), 'pins', ['id'], unique=False)
    op.add_column('users', sa.Column('pin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'pins', ['pin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'pin_id')
    op.drop_index(op.f('ix_pins_id'), table_name='pins')
    op.drop_table('pins')
    # ### end Alembic commands ###
